version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    network_mode: service:influxdb
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ../.docker/influxdb/data/:/var/lib/influxdb2/
      - ../.docker/influxdb/config/:/etc/influxdb2/
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: codern
      DOCKER_INFLUXDB_INIT_BUCKET: gateway
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: this_is_token
