version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ../.docker/influxdb/data/:/var/lib/influxdb2/
      - ../.docker/influxdb/config/:/etc/influxdb2/
    network_mode: service:app
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: codern
      DOCKER_INFLUXDB_INIT_BUCKET: gateway
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: this_is_token
  mysql:
    image: mysql:8
    volumes:
      - ../.docker/mysql/:/var/lib/mysql/
    network_mode: service:app
    environment:
      MYSQL_ROOT_PASSWORD: password
