version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../:/workspace:cached
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ./.docker/influxdb/data/:/var/lib/influxdb2/
      - ./.docker/influxdb/config/:/etc/influxdb2/
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: codern
      DOCKER_INFLUXDB_INIT_BUCKET: api
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 81:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
  seaweedfs-master:
    image: chrislusf/seaweedfs:dev
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=seaweedfs-master -ip.bind=0.0.0.0"
  seaweedfs-volume:
    image: chrislusf/seaweedfs:dev
    ports:
      - 8080:8080
      - 18080:18080
    volumes:
      - ./.docker/seaweedfs/volume/:/data/volume/
    command: 'volume -dir=/data/volume -mserver="seaweedfs-master:9333" -ip.bind=0.0.0.0 -port=8080'
    depends_on:
      - seaweedfs-master
  seaweedfs-filer:
    image: chrislusf/seaweedfs:dev
    ports:
      - 8888:8888
      - 18888:18888
    volumes:
      - ./.docker/seaweedfs/filerldb2/:/data/filerldb2/
    command: 'filer -master="seaweedfs-master:9333" -ip.bind=0.0.0.0'
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - 4000:3000
    volumes:
      - ./.docker/grafana:/var/lib/grafana/
