CREATE TABLE IF NOT EXISTS `survey` (
  `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `user_id` VARCHAR(64) NOT NULL,
  `message` TEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES `user`(`id`)
);
