name: Build and publish image

on:
  workflow_call:
    inputs:
      name:
        description: Image name
        type: string
        required: true
      tag:
        description: Image tag
        type: string
        required: true
      ref:
        description: Git ref to checkout
        type: string
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      
      - name: Login to the container registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VERSION=${{ inputs.tag }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ inputs.name }}:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
