name: Release with versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.versioning.outputs.new_tag }}
      changelog: ${{ steps.versioning.outputs.changelog }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version and tag
        id: versioning
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

  build-and-push:
    name: Build and publish image
    needs:
      - versioning
    uses: ./.github/workflows/publish-image.yaml
    with:
      name: ${{ github.repository }}
      tag: ${{ needs.versioning.outputs.tag }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - versioning
      - build-and-push
    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.versioning.outputs.tag }}
          name: ${{ needs.versioning.outputs.tag }}
          body: ${{ needs.versioning.outputs.changelog }}
